### ISSUE TITLE
Improve header group matching pattern

### ISSUE THREAD

**Issue by iby** [luckymarmot/Paw-cURLImporter#20]
I'm playing with dropbox api, there's a funny `:authority` header, which errors the import because it starts with `:`, which is not taken into account in:

```js
function _parseHeader(headers) {
    var arg = this._popArg();
    var m = arg.match(/^([^\:\s]+)\s*\:\s*([\s\S]*)$/);
    if (!m) {
        throw new Error('Invalid -H/--header value: ' + arg);
    }
    return headers.set(this._normalizeHeader(m[1]), this._formatParameter(this._normalizeHeader(m[1]), m[2]));
}
```

Please use the non-greedy regex `/^(.+?)\s*\:\s*([\s\S]*)$/` to match the header name. Happy to make the pr.

**Comment by mittsh** [comment]
@ianbytchek Thanks a lot for the suggestion. I agree that non-greedy regexp should do the job.

It's worth mentioning that Dropbox isn't exactly respecting [RFC 2616](https://www.ietf.org/rfc/rfc2616.txt). In paragraph 4.2 "Message Headers", a header name (`field-name`) should be a `token`, and as per paragraph 2.2:

```
       token          = 1*<any CHAR except CTLs or separators>
       separators     = "(" | ")" | "<" | ">" | "@"
                      | "," | ";" | ":" | "\" | <">
                      | "/" | "[" | "]" | "?" | "="
                      | "{" | "}" | SP | HT
```

I find it a little sad that Dropbox isn't following the spec by making this (confusing) choice of header name. For curiosity, do you have a link to the Dropbox API doc page where it's mentioned, I couldn't find it quickly Googling it?

Otherwise, yeah a PR would be more than welcome 😄  Thanks much!

**Comment by JonathanMontane** [comment]
@mittsh @ianbytchek RFC 2616 was superseded in [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.2), which is even more restrictive in the formatting of the header than 2616.

I concur with @mittsh, could provide us with a link to the corresponding documentation page of the dropbox api, where this is described ? It sounds more like a bug than a feature to me.

```
section 3.2:
header-field   = field-name ":" OWS field-value OWS

     field-name     = token
     field-value    = *( field-content / obs-fold )
     field-content  = field-vchar [ 1*( SP / HTAB ) field-vchar ]
     field-vchar    = VCHAR / obs-text

     obs-fold       = CRLF 1*( SP / HTAB )
                    ; obsolete line folding
                    ; see Section 3.2.4

Section 3.2.6:
     token          = 1*tchar

     tchar          = "!" / "#" / "$" / "%" / "&" / "'" / "*"
                    / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
                    / DIGIT / ALPHA
                    ; any VCHAR, except delimiters

Delimiters are chosen from the set of US-ASCII visual characters not allowed
in a token (DQUOTE and "(),/:;<=>?@[\]{}").
```

**Comment by iby** [comment]
Thanks @mittsh and @JonathanMontane. This is not-yet public mobile api.

![2017-03-22 14 24 32](https://cloud.githubusercontent.com/assets/1086845/24193324/57329b82-0f0b-11e7-9418-2a460391702f.gif)

I'm fully on the side of following conventions and what Dropbox does is a total crime. However, and most importantly, cURL itself works with such headers. Secondly, this is a cURL importer and not RFC validator. If you feel the moral part is applicable here, perhaps the plugin can issue a slap on the hands warning, but not fail all together? 😄

**Comment by JonathanMontane** [comment]
new release fixing this bug:
https://github.com/luckymarmot/Paw-cURLImporter/releases/tag/v2.2.17

**Comment by JonathanMontane** [comment]
the release has been published in paw's db, so it should automatically update within the next few hours.

**Comment by mittsh** [comment]
@JonathanMontane Cool 👏 

> If you feel the moral part is applicable here, perhaps the plugin can issue a slap on the hands warning, but not fail all together?

@ianbytchek No moral duty towards RFCs :) I'm just always a little worried about being too tolerant on parsing user entries, since it sometimes have consequences and things may fail down the road. But I guess this one is very safe and it's good that we follow the robustness motto "Be conservative in what you send, be liberal in what you accept" 😄

**Comment by mittsh** [comment]
Also, you can force the extension update in Paw menu > Extensions > Check for Extensions Updates… @ianbytchek

**Comment by iby** [comment]
> I'm just always a little worried about being too tolerant on parsing user entries, since it sometimes have consequences and things may fail down the road. 

@mittsh I sensed that, haha! But ain't no my fault! 😄

**Comment by JonathanMontane** [comment]
@ianbytchek if you import the previous incriminating curl request, you should see that it works, and also that a warning has been written in the extensions console (⌘ ⌥ 3)
